# Generated by Django 4.2.1 on 2023-05-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1-semester'), ('2', '2-semester'), ('3', '3-semester'), ('4', '4-semester'), ('5', '5-semester'), ('6', '6-semester'), ('7', '7-semester'), ('8', '8-semester')], max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lessons_count', models.IntegerField()),
            ],
        ),
    ]
