# Generated by Django 4.2.1 on 2023-05-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hemis', '0002_science'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemis.science')),
            ],
        ),
    ]
